# Generated by Django 4.2.3 on 2023-08-04 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('nome_ingrediente', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome_receita', models.CharField(max_length=100)),
                ('modo_preparo', models.TextField(default='*')),
                ('tempo_preparo', models.IntegerField(default=0)),
                ('link_youtube', models.URLField(null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Receitas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receita.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes_receita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.CharField(max_length=100)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='receita.ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='receita.receita')),
            ],
        ),
    ]
