# Generated by Django 4.2.3 on 2023-08-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.ManyToManyField(through='receita.Ingredientes_receita', to='receita.ingrediente'),
        ),
    ]
