# Generated by Django 4.2.3 on 2023-08-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_receita_ingredientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredientes_receita',
            new_name='IngredientesReceita',
        ),
    ]
